Repository gridsuite/gridmerge-app, pull requests merged in 2020-10, with the labels that each got.

#17 Apps metadata (urls & colors) | for topbar menu
  .env
  app-httpd.conf
  package-lock.json
  package.json
  public/env.json
  src/components/app.js
  src/setupProxy.js
  src/utils/api.js
Labels: Depends on other PRs

#13 Add timeline
  package-lock.json
  package.json
  src/components/app.js
  src/components/country-state-item.js
  src/components/country-state-list.js
  src/components/merge-map.js
  src/components/process.js
  src/components/stepper.js
  src/components/timeline.js
  src/images/clock.svg
  src/redux/actions.js
  src/redux/reducer.js
  src/utils/api.js
Labels: L, Urgent

#30 Fix warning
  src/components/country-state-item.js
  src/components/process.js
  src/components/timeline.js
Labels: Bug, S
