Repository gridsuite/gridmerge-app, pull requests merged in 2021-01, with the labels that each got.

#41 Add toggle mode for display timeline labels
  src/components/app.js
  src/components/parameters.js
  src/components/timeline.js
  src/redux/actions.js
  src/redux/local-storage.js
  src/redux/reducer.js
  src/translations/en.json
  src/translations/fr.json
Labels: M

#39 move config params to back
  src/components/app.js
  src/components/parameters.js
  src/redux/actions.js
  src/redux/local-storage.js
  src/redux/reducer.js
  src/utils/api.js
  src/utils/config-params.js
Labels: functionally tested

#43 Show message with snackbar
  src/components/app.js
  src/components/process.js
Labels: S
